### ISSUE TITLE
AuthenticationError(LoginFailed(BadCredentials))

### ISSUE THREAD

**Issue by koinoniaOG916** [codetheweb/aoede#58]
This error has been persistent for the last while.

Double checked my login credentials, and all is correct. Reset the Bot token and made sure the user ID is correct. The logs show as follows: 

thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/lib/player.rs:233:14:
Error creating session: AuthenticationError(LoginFailed(BadCredentials))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Anyone who shed some light on this error? Is this an issue with Aoede?

**Comment by DerP4si** [comment]
same

**Comment by TheRoyalGhost45** [comment]
same

**Comment by DerP4si** [comment]
same as #54

**Comment by Hippotumux** [comment]
same It's hopeless ..

**Comment by codebyant** [comment]
same...

**Comment by TheRoyalGhost45** [comment]
same

**Comment by NekomataGami** [comment]
getting the same error

**Comment by gmail-random1** [comment]
same... 😭

**Comment by Cardrhyme206113** [comment]
same...

**Comment by mrhashishah** [comment]
Same

**Comment by endrence3** [comment]
It is likely that the issue arises from recent changes to Spotify's API endpoints, while the current version of the bot's Spotify package is outdated.

**Comment by mattdayinbound** [comment]
getting the same error

**Comment by zachlagden** [comment]
**This is caused by Spotify deprecating username/password authentication in 2024.** The "BadCredentials" error is now affecting all librespot-based applications regardless of valid credentials.

**Root Cause:** Spotify changed their authentication flow around July 2024, disabling the username/password method that librespot 0.4.2 relies on. This affects the entire ecosystem (spotifyd, ncspot, etc.).

**Solution:** I've created a fork that implements cached credentials authentication using librespot-auth as a workaround: https://github.com/zachlagden/aoede

**Quick Fix:**
1. Download librespot-auth from my fork
2. Generate credentials via Spotify Connect (no username/password needed)
3. Use the cached credentials instead

This bypasses Spotify's deprecated authentication entirely. The fix is backward compatible and includes detailed migration instructions in the README.

**Note:** The original project would need to update to librespot 0.6.0+ and implement token-based authentication to resolve this properly, but my fork provides an immediate solution using the existing librespot 0.4.2.
